builds:
  - id: karmabot
    binary: karmabot
    main: ./cmd/karmabot/main.go
    ldflags: -s -w -X "github.com/kamaln7/karmabot.Version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
  - id: karmabotctl
    binary: karmabotctl
    main: ./cmd/karmabotctl/main.go
    ldflags: -s -w -X "github.com/kamaln7/karmabot.Version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - binaries:
      - karmabot
    dockerfile: ./cmd/karmabot/Dockerfile-goreleaser
    image_templates:
      - "kamaln7/karmabot:{{ .Version }}"
      - "kamaln7/karmabot:latest"
  - binaries:
      - karmabot
    dockerfile: ./cmd/karmabot/Dockerfile-webui-goreleaser
    image_templates:
      - "kamaln7/karmabot:{{ .Version }}-webui"
      - "kamaln7/karmabot:latest-webui"
    extra_files:
      - www
  - binaries:
      - karmabotctl
    dockerfile: ./cmd/karmabotctl/Dockerfile-goreleaser
    image_templates:
      - "kamaln7/karmabotctl:{{ .Version }}"
      - "kamaln7/karmabotctl:latest"