FROM alpine:3.6
RUN apk add --no-cache sqlite ca-certificates
# See http://stackoverflow.com/questions/34729748/installed-go-binary-not-found-in-path-on-alpine-linux-docker
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
COPY karmabot /
ENTRYPOINT ["/karmabot"]
